### PR TITLE
osu-lazer-bin: adding support for darwin systems

### PR DESCRIPTION
**Pull request by stepbrobd**
###### Description of changes

This patch added osu-lazer-bin support for Darwin systems. I have tested the build on aarch64-darwin, x86_64-darwin and x86_64-linux with Debian.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by delan** [comment]
Thanks for adding this! I’ll rebase this onto my patch to make the changes easier to see, then I’ll squash and merge.

**Comment by delan** [comment]
Thanks for adding this! I tried rebasing your patch onto mine to make the changes easier to see, but it looks like I don’t have permission to push to your branch. I then tried rebasing mine forward to save you from having to change yours, but I think I did the exact opposite of that. Could you please rebase onto mine?

```
$ git fetch git@github.com:delan/nixpkgs.git osu-lazer
$ git rebase FETCH_HEAD
$ git checkout --theirs pkgs/games/osu-lazer/bin.nix
$ git add pkgs/games/osu-lazer/bin.nix
$ git rebase --continue
```

**Comment by stepbrobd** [comment]
Thanks for the instructions!

I should have done that at the beginning, sorry about the inconvenience.

**Comment by stepbrobd** [comment]
@ofborg eval

**Comment by delan** [comment]
Sorry, my patch got merged before I saw this. I’ll reopen this upstream with the [suggested update script](https://github.com/NixOS/nixpkgs/pull/219192#issuecomment-1454684724).

**Pull request merged**
